# -*- coding: utf-8 -*-

# Authors:	Roman Rivera (Invisible Institute)
# individual/roster__2018-03_p441436/clean/src/Makefile

.PHONY: all clean
# Additional files created: clean.log, clean.yaml

all: \
		output/roster__2018-03.csv.gz

output/roster__2018-03.csv.gz: \
		src/clean.py \
		input/roster__2018-03.csv.gz
	python $<


clean:
	rm output/*


# done
