# -*- coding: utf-8 -*-

# Authors:	Roman Rivera
# individual/p050032_all-members-rank/all-members/import/Makefile

.PHONY: all clean

all:
		src/import.py \
		input/all-members.csv \
		output/all-members.csv \
	python $<

clean: rm output/*	

# done